# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
arr = np.zeros((10))

3. Create a vector with values ranging from 10 to 49

In [3]:
rng = np.arange(10,49)

4. Find the shape of previous array in question 3

In [4]:
rng.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
rng.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [7]:
print(rng.ndim)

1


8. Create a boolean array with all the True values

In [8]:
boolean = np.ones((10),dtype=bool)

9. Create a two dimensional array




In [9]:
twoDim = np.zeros((10,10))
print(twoDim.ndim)

2


10. Create a three dimensional array



In [10]:
threedim = np.zeros((10,10,10))
print(threedim.ndim)

3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
reverse = np.random.randn((10))
print(reverse)
reverse = np.flip(reverse)
print(reverse)

[-0.46954462 -1.11476422 -0.34774951  1.42072827 -0.17227768 -0.85706922
  0.44668853  0.87560176 -0.44015905 -0.22783064]
[-0.22783064 -0.44015905  0.87560176  0.44668853 -0.85706922 -0.17227768
  1.42072827 -0.34774951 -1.11476422 -0.46954462]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
nullVector = np.array([1 if x == 4 else 0 for x in range(10)])
print(nullVector)

[0 0 0 0 1 0 0 0 0 0]


13. Create a 3x3 identity matrix

In [13]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1,2,3,4,5],dtype=float)
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1 == arr2
print(arr3)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [17]:
odd = np.arange(0,10)
print(odd[odd % 2 != 0])

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [18]:
odd[odd % 2 != 0] = -1
print(odd)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
twoD = np.ones((4,4))
twoD[1:-1,1:-1] = 0
print(twoD)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d = np.where(arr2d == 5,12,arr2d)
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
])
arr3d[0][0] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[0]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[:,2]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
rand = np.random.randn((100)).reshape((10,10))
print(f"Minimun Value {np.amin(rand)}")
print(f"Maximum Value {np.amax(rand)}")

Minimun Value -2.2837477221381985
Maximum Value 2.5620789179742998


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f"Common Elements are : {np.intersect1d(a,b)}")

Common Elements are : [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
np.searchsorted(a, np.intersect1d(a, b))

array([1, 5], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print('==================================================')
print(data[names != 'Will'])

[[ 0.79529215 -0.97741749 -0.0115015   0.62815036]
 [ 1.47258734  0.64927411  0.38251237 -0.1831414 ]
 [-0.59991043 -2.07044163 -1.97703271  0.4341415 ]
 [ 2.57267336  0.13793104 -0.0630175  -1.27429978]
 [-0.49516058  0.16005144  0.1652926   1.12793848]
 [-0.4754079  -1.39395656 -1.16842394  0.25117908]
 [-0.52900326  0.37646031  1.58657871 -1.8663994 ]]
[[ 0.79529215 -0.97741749 -0.0115015   0.62815036]
 [ 1.47258734  0.64927411  0.38251237 -0.1831414 ]
 [ 2.57267336  0.13793104 -0.0630175  -1.27429978]
 [-0.4754079  -1.39395656 -1.16842394  0.25117908]
 [-0.52900326  0.37646031  1.58657871 -1.8663994 ]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
print(data)
print('==================================================')
mask = (names != 'Will') & (names!= 'Joe')
print(data[mask])

[[ 0.79529215 -0.97741749 -0.0115015   0.62815036]
 [ 1.47258734  0.64927411  0.38251237 -0.1831414 ]
 [-0.59991043 -2.07044163 -1.97703271  0.4341415 ]
 [ 2.57267336  0.13793104 -0.0630175  -1.27429978]
 [-0.49516058  0.16005144  0.1652926   1.12793848]
 [-0.4754079  -1.39395656 -1.16842394  0.25117908]
 [-0.52900326  0.37646031  1.58657871 -1.8663994 ]]
[[ 0.79529215 -0.97741749 -0.0115015   0.62815036]
 [ 2.57267336  0.13793104 -0.0630175  -1.27429978]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[ 7.81446439 10.43375573 10.16551344]
 [ 7.62760006  4.34657656  9.78630061]
 [ 2.65405128  1.93917704  5.15795405]
 [ 1.30546528  1.22005902 10.89347907]
 [ 6.2359925  14.52031755  3.10523591]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
rand_arr2 = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr2)

[[[15.15473342  7.0006862   6.73750864  3.20200098]
  [ 6.91905867  2.75517021 10.44271079  7.32215179]]

 [[ 1.31953923 11.49166214 15.00252242 12.36304854]
  [ 5.01844487 12.6056016  10.87239401 15.91025734]]]


33. Swap axes of the array you created in Question 32

In [33]:
print("Original Array")
print(rand_arr2)
print("Swapped Axes")
print(np.swapaxes(rand_arr2, 2, 0))

Original Array
[[[15.15473342  7.0006862   6.73750864  3.20200098]
  [ 6.91905867  2.75517021 10.44271079  7.32215179]]

 [[ 1.31953923 11.49166214 15.00252242 12.36304854]
  [ 5.01844487 12.6056016  10.87239401 15.91025734]]]
Swapped Axes
[[[15.15473342  1.31953923]
  [ 6.91905867  5.01844487]]

 [[ 7.0006862  11.49166214]
  [ 2.75517021 12.6056016 ]]

 [[ 6.73750864 15.00252242]
  [10.44271079 10.87239401]]

 [[ 3.20200098 12.36304854]
  [ 7.32215179 15.91025734]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr = np.random.uniform(0,20, size=(10))
arr = arr.astype('int32') 
arr =np.sqrt(arr)
arr = np.where(arr < 0.5, 0, arr)
arr = arr.astype('int32')
print(arr)

[3 3 4 2 2 2 2 3 1 2]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
arr = np.random.uniform(0,20, size=(10))
arr1 = np.random.uniform(0,20, size=(10))
newArr = np.maximum(arr,arr1)
print(f"Array 1 : {arr}")
print(f"Array 2 : {arr1}")
print(f"New Array : {newArr}")


Array 1 : [ 2.60253676  7.30885072 18.01068431  8.59087495 13.64285454 17.42513991
  8.04970923 13.55299142 13.69942044  4.64221238]
Array 2 : [ 9.5375168   4.53542701  1.99919546  7.36975435 19.54735766  3.25443618
  4.78978505 13.30194616  5.90724213  5.67375285]
New Array : [ 9.5375168   7.30885072 18.01068431  8.59087495 19.54735766 17.42513991
  8.04970923 13.55299142 13.69942044  5.67375285]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a, b)
print(c)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([
    [34,43,73],
    [82,22,12],
    [53,94,66]
])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 2, axis=1)
sampleArray = np.insert(sampleArray, 2, newColumn, axis=1)
print(sampleArray)

[[34 43 10]
 [82 22 10]
 [53 94 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
arr = np.random.uniform(1,20,size=(4,5))
arr = arr.astype('int32')
print(arr.cumsum())

[ 18  25  27  33  48  55  59  62  73  88  96 114 130 143 159 171 187 189
 201 210]
